name: Update test.m3u

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest M3U
        run: |
          curl -L --fail --retry 3 \
          "https://dl.dropboxusercontent.com/scl/fi/0h8tyzzzubhmepl9gzx1m/kanka.m3u?rlkey=4gdlpapjunpneo5w7k3h2z1qj&st=tdbbbca0.m3u" \
          -o kanka.m3u

      - name: Commit only if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add kanka.m3u

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update test.m3u"
            git push
          fi
